### ISSUE TITLE
Hi , how to use AsyncTask in search, create method

### ISSUE THREAD

**Issue by yokikathir** [oogbox/odoo-mobile-api#24] opened 2019-04-08 06:01 UTC
i attached the sample code.
`OdooFields fields = new OdooFields();
            fields.addAll("season_id", "section_id", "division_id", "section_officer", "monthly_target_acres", "achieved_target_acres", "remain_target_acres", "target_acres", "committed_acres", "actual_acres", "state", "target_for", "check_box", "id","crop_type_id","months");
            int offset = 0;
            int limit = 100000;
            String sorting = "";
            client.searchRead("section.target.line", null, fields, offset, limit, "", new IOdooResponse() {
                @Override
                public void onResult(OdooResult result) {
                    OdooRecord[] records = result.getRecords();
                    AmtPref.getInstance().writeString(Keys.LAST_SYNC_SECTION_TARGET_LINE, AppUtils.getCurrentDateSync());
                    for (OdooRecord record : records) {
                        Log.e("targetline>>", record.getString("target_acres"));
                        Log.e("targetlineseason>>", record.getString("season_id"));
                        SectionTargetLine masterDb = new SectionTargetLine(record.getString("season_id"), record.getString("section_id"), record.getString("division_id"), record.getString("section_officer"), record.getString("monthly_target_acres"), record.getString("achieved_target_acres"), record.getString("remain_target_acres"), record.getString("target_acres"), record.getString("committed_acres"), record.getString("actual_acres"), record.getString("state"), record.getString("target_for"), record.getString("check_box"), record.getInt("id"),record.getString("crop_type_id"),record.getString("months"));
                        masterDb.save();
                    }

                }
            });`

**Comment by bunny-oogbox** [comment] 2019-04-12 03:50
Closing issue as its duplicate of https://github.com/oogbox/odoo-mobile-api/issues/23
See comment https://github.com/oogbox/odoo-mobile-api/issues/23#issuecomment-482425916

**Closed by bunny-oogbox** 2019-04-12 03:50 UTC
